service: hello-serverless

provider:
  name: faas
  runtime: node

functions:
  hello-serverless:
    handler: ./function
    image: hello-serverless
    lang: node

plugins:
  - serverless-faas

package:
  artifact: none
